export const ageRanges = ["18-39", "40-49", "50-53", "54", "55-59"].map((label) => ({ id: label, label }));
export type AgeId = (typeof ageRanges)[number]["id"];

export interface ILifeInsuranceComparisonOffer {
  [ageRange: AgeId]: LifeInsuranceComparisonRow[];
}

export interface LifeInsuranceComparisonRow {
  name: string;
  pzu: string | number | null;
  hestia: string | number | null;
  warta: string | number | null;
}

export const lifeInsuranceComparisonOffer: ILifeInsuranceComparisonOffer = {
  "18-39": [
    {
      name: "składka miesięczna",
      pzu: "93",
      hestia: "103",
      warta: "99",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym w pracy",
      pzu: "190000",
      hestia: "220000",
      warta: "175000",
    },
    {
      name: "śmierć spowodowana wypadkiem w pracy",
      pzu: "150000",
      hestia: "150000",
      warta: "110000",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym",
      pzu: "150000",
      hestia: "150000",
      warta: "145000",
    },
    {
      name: "śmierć spowodowana nieszczęśliwym wypadkiem (NW)",
      pzu: "110000",
      hestia: "100000",
      warta: "85000",
    },
    {
      name: "śmierć spowodowana zawałem serce lub udarem mózgu",
      pzu: "40000",
      hestia: "65000",
      warta: "80000",
    },
    {
      name: "śmierć niezależnie od przyczyny",
      pzu: "40000",
      hestia: "50000",
      warta: "35000",
    },
    {
      name: "zachorowanie na ciężką chorobę",
      pzu: "3000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "zachorowanie na nowotwór złośliwy",
      pzu: "9000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "wystąpienie nowotworu we wczesnym stadium",
      pzu: "5000",
      hestia: null,
      warta: null,
    },
    {
      name: "leczenie specjalistyczne",
      pzu: "2000",
      hestia: "2500",
      warta: "2000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku zawału serca lub udaru śródmózgowego -za 1% uszczerbku",
      pzu: null,
      hestia: "400",
      warta: null,
    },
    {
      name: "usługi assistance",
      pzu: "TAK",
      hestia: "NIE",
      warta: null,
    },
    {
      name: "Lecznie szpitalne (skumulowane kwoty świadczeń):",
      pzu: null,
      hestia: null,
      warta: null,
    },
    {
      name: "za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "60/120",
      hestia: "70/180",
      warta: "80/160",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku komunikacyjngo przy pracy",
      pzu: "120",
      hestia: "330",
      warta: "440",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku przy pracy",
      pzu: "120",
      hestia: "180",
      warta: "250",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku NW w ruchu lądowym, wodnym lub powietrznym",
      pzu: "120",
      hestia: "330",
      warta: "330",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku zawału serca lub krwotoku śródmózgowego-za 1%",
      pzu: "60",
      hestia: "140",
      warta: "150",
    },
    {
      name: "pobyt na OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "500",
    },
    {
      name: "Opracja chirurgiczna:",
      pzu: null,
      hestia: null,
      warta: "s.u. 2000",
    },
    {
      name: "I klasa",
      pzu: "1500",
      hestia: "2000",
      warta: null,
    },
    {
      name: "II klasa",
      pzu: "750",
      hestia: "1200",
      warta: null,
    },
    {
      name: "III klasa",
      pzu: "500",
      hestia: "400",
      warta: null,
    },
    {
      name: "IVklasa",
      pzu: "150",
      hestia: null,
      warta: null,
    },
    {
      name: "Vklasa",
      pzu: "75",
      hestia: null,
      warta: null,
    },
    {
      name: "całkowita niezdolność do pracy ubezpieczonego w wyniku NW",
      pzu: null,
      hestia: "40000",
      warta: "45000",
    },
    {
      name: "niezdolność do samodzilnej egzystencji",
      pzu: null,
      hestia: null,
      warta: "15000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku NW-za 1% trwałego uszczerbku",
      pzu: "300",
      hestia: "500",
      warta: "480",
    },
    {
      name: "śmierć małżonka w wyniku NW komunikacyjnego",
      pzu: "20000",
      hestia: "24000",
      warta: "30000",
    },
    {
      name: "śmierć małżonka w wyniku NW",
      pzu: "20000",
      hestia: "24000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka w wyniku zawału serca lub udaru mózgu",
      pzu: "10000",
      hestia: "12000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka niezależnie od przyczyny",
      pzu: "10000",
      hestia: "12000",
      warta: "10000",
    },
    {
      name: "trwałe inwalidztwo małżonka/partnera w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "ciężka choroba małżonka/partnera",
      pzu: "3000",
      hestia: "3000",
      warta: null,
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku choroby/NW",
      pzu: "50/100",
      hestia: null,
      warta: "40/100",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "200",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku zawału serca/udaru mózgu",
      pzu: "50",
      hestia: null,
      warta: "100",
    },
    {
      name: "pobyt małżonka/partnerana OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "400",
    },
    {
      name: "osierocenie dziecka",
      pzu: null,
      hestia: "4000",
      warta: "300",
    },
    {
      name: "urodzenie dziecka",
      pzu: "1000",
      hestia: "1300",
      warta: "1000",
    },
    {
      name: "urodzenie marwego dziecka",
      pzu: null,
      hestia: "2600",
      warta: null,
    },
    {
      name: "wada wrodzona dziecka",
      pzu: null,
      hestia: "2500",
      warta: "3000",
    },
    {
      name: "trwałe inwalidztwo dziecka w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "śmierć dziecka spowodowana NW",
      pzu: "6000",
      hestia: "10000",
      warta: "6000",
    },
    {
      name: "śmierć dziecka niezależnie od przyczyny",
      pzu: "3000",
      hestia: "5000",
      warta: "3000",
    },
    {
      name: "ciężka choroba dziacka",
      pzu: "4000",
      hestia: "5000",
      warta: "4000",
    },
    {
      name: "leczenie szpitalne dziecka-za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "50/100",
      hestia: "500 (kwota zryczałtowana)",
      warta: "40/100",
    },
    {
      name: "rekonwalescencja",
      pzu: null,
      hestia: null,
      warta: "1000",
    },
    {
      name: "śmierć noworodka",
      pzu: null,
      hestia: null,
      warta: "3000",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera spowodowana NW",
      pzu: "3000",
      hestia: "1600",
      warta: "3500",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera niezależnie od przyczyny",
      pzu: "1200",
      hestia: "1600",
      warta: "1500",
    },
  ],
  "40-49": [
    {
      name: "składka miesięczna",
      pzu: "93",
      hestia: "103",
      warta: "111",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym w pracy",
      pzu: "190000",
      hestia: "220000",
      warta: "175000",
    },
    {
      name: "śmierć spowodowana wypadkiem w pracy",
      pzu: "150000",
      hestia: "150000",
      warta: "110000",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym",
      pzu: "150000",
      hestia: "150000",
      warta: "145000",
    },
    {
      name: "śmierć spowodowana nieszczęśliwym wypadkiem (NW)",
      pzu: "110000",
      hestia: "100000",
      warta: "85000",
    },
    {
      name: "śmierć spowodowana zawałem serce lub udarem mózgu",
      pzu: "40000",
      hestia: "65000",
      warta: "80000",
    },
    {
      name: "śmierć niezależnie od przyczyny",
      pzu: "40000",
      hestia: "50000",
      warta: "35000",
    },
    {
      name: "zachorowanie na ciężką chorobę",
      pzu: "3000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "zachorowanie na nowotwór złośliwy",
      pzu: "9000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "wystąpienie nowotworu we wczesnym stadium",
      pzu: "5000",
      hestia: null,
      warta: null,
    },
    {
      name: "leczenie specjalistyczne",
      pzu: "2000",
      hestia: "do 2500",
      warta: "2000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku zawału serca lub udaru śródmózgowego -za 1% uszczerbku",
      pzu: null,
      hestia: "400",
      warta: null,
    },
    {
      name: "usługi assistance",
      pzu: "TAK",
      hestia: "NIE",
      warta: null,
    },
    {
      name: "Lecznie szpitalne (skumulowane kwoty świadczeń):",
      pzu: null,
      hestia: null,
      warta: null,
    },
    {
      name: "za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "60/120",
      hestia: "70/180",
      warta: "80/160",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku komunikacyjngo przy pracy",
      pzu: "120",
      hestia: "330",
      warta: "440",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku przy pracy",
      pzu: "120",
      hestia: "180",
      warta: "250",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku NW w ruchu lądowym, wodnym lub powietrznym",
      pzu: "120",
      hestia: "330",
      warta: "330",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku zawału serca lub krwotoku śródmózgowego-za 1%",
      pzu: "60",
      hestia: "140",
      warta: "150",
    },
    {
      name: "pobyt na OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "500",
    },
    {
      name: "Opracja chirurgiczna:",
      pzu: null,
      hestia: null,
      warta: "s.u. 2000",
    },
    {
      name: "I klasa",
      pzu: "1500",
      hestia: "2000",
      warta: null,
    },
    {
      name: "II klasa",
      pzu: "750",
      hestia: "1200",
      warta: null,
    },
    {
      name: "III klasa",
      pzu: "500",
      hestia: "400",
      warta: null,
    },
    {
      name: "IVklasa",
      pzu: "1500",
      hestia: null,
      warta: null,
    },
    {
      name: "Vklasa",
      pzu: "75",
      hestia: null,
      warta: null,
    },
    {
      name: "całkowita niezdolność do pracy ubezpieczonego w wyniku NW",
      pzu: null,
      hestia: "40000",
      warta: "45000",
    },
    {
      name: "niezdolność do samodzilnej egzystencji",
      pzu: null,
      hestia: null,
      warta: "15000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku NW-za 1% trwałego uszczerbku",
      pzu: "300",
      hestia: "500",
      warta: "480",
    },
    {
      name: "śmierć małżonka w wyniku NW komunikacyjnego",
      pzu: "20000",
      hestia: "24000",
      warta: "30000",
    },
    {
      name: "śmierć małżonka w wyniku NW",
      pzu: "20000",
      hestia: "24000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka w wyniku zawału serca lub udaru mózgu",
      pzu: "10000",
      hestia: "12000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka niezależnie od przyczyny",
      pzu: "10000",
      hestia: "12000",
      warta: "10000",
    },
    {
      name: "trwałe inwalidztwo małżonka/partnera w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "ciężka choroba małżonka/partnera",
      pzu: "3000",
      hestia: "3000",
      warta: null,
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku choroby/NW",
      pzu: "50/100",
      hestia: null,
      warta: "40/100",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "200",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku zawału serca/udaru mózgu",
      pzu: "50",
      hestia: null,
      warta: "100",
    },
    {
      name: "pobyt małżonka/partnerana OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "400",
    },
    {
      name: "osierocenie dziecka",
      pzu: null,
      hestia: "4000",
      warta: "300",
    },
    {
      name: "urodzenie dziecka",
      pzu: "1000",
      hestia: "1300",
      warta: "1000",
    },
    {
      name: "urodzenie marwego dziecka",
      pzu: null,
      hestia: "2600",
      warta: null,
    },
    {
      name: "wada wrodzona dziecka",
      pzu: null,
      hestia: "2500",
      warta: "3000",
    },
    {
      name: "trwałe inwalidztwo dziecka w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "śmierć dziecka spowodowana NW",
      pzu: "6000",
      hestia: "10000",
      warta: "6000",
    },
    {
      name: "śmierć dziecka niezależnie od przyczyny",
      pzu: "3000",
      hestia: "5000",
      warta: "3000",
    },
    {
      name: "ciężka choroba dziacka",
      pzu: "4000",
      hestia: "5000",
      warta: "4000",
    },
    {
      name: "leczenie szpitalne dziecka-za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "50/100",
      hestia: "500 (kwota zryczałtowana)",
      warta: "40/100",
    },
    {
      name: "rekonwalescencja",
      pzu: null,
      hestia: null,
      warta: "1000",
    },
    {
      name: "śmierć noworodka",
      pzu: null,
      hestia: null,
      warta: "3000",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera spowodowana NW",
      pzu: "3000",
      hestia: "1600",
      warta: "3500",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera niezależnie od przyczyny",
      pzu: "1200",
      hestia: "1600",
      warta: "1500",
    },
  ],
  "50-53": [
    {
      name: "składka miesięczna",
      pzu: "93",
      hestia: "103",
      warta: "111",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym w pracy",
      pzu: "190000",
      hestia: "220000",
      warta: "175000",
    },
    {
      name: "śmierć spowodowana wypadkiem w pracy",
      pzu: "150000",
      hestia: "150000",
      warta: "110000",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym",
      pzu: "130000",
      hestia: "150000",
      warta: "145000",
    },
    {
      name: "śmierć spowodowana nieszczęśliwym wypadkiem (NW)",
      pzu: "90000",
      hestia: "100000",
      warta: "85000",
    },
    {
      name: "śmierć spowodowana zawałem serce lub udarem mózgu",
      pzu: "20000",
      hestia: "65000",
      warta: "80000",
    },
    {
      name: "śmierć niezależnie od przyczyny",
      pzu: "20000",
      hestia: "50000",
      warta: "35000",
    },
    {
      name: "zachorowanie na ciężką chorobę",
      pzu: "3000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "zachorowanie na nowotwór złośliwy",
      pzu: "9000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "wystąpienie nowotworu we wczesnym stadium",
      pzu: "5000",
      hestia: null,
      warta: null,
    },
    {
      name: "leczenie specjalistyczne",
      pzu: "2000",
      hestia: "do 2500",
      warta: "2000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku zawału serca lub udaru śródmózgowego -za 1% uszczerbku",
      pzu: null,
      hestia: "400",
      warta: null,
    },
    {
      name: "usługi assistance",
      pzu: "TAK",
      hestia: "NIE",
      warta: null,
    },
    {
      name: "Lecznie szpitalne (skumulowane kwoty świadczeń):",
      pzu: null,
      hestia: null,
      warta: null,
    },
    {
      name: "za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "60/120",
      hestia: "70/180",
      warta: "80/160",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku komunikacyjngo przy pracy",
      pzu: "120",
      hestia: "330",
      warta: "440",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku przy pracy",
      pzu: "120",
      hestia: "180",
      warta: "250",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku NW w ruchu lądowym, wodnym lub powietrznym",
      pzu: "120",
      hestia: "330",
      warta: "330",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku zawału serca lub krwotoku śródmózgowego-za 1%",
      pzu: "60",
      hestia: "140",
      warta: "150",
    },
    {
      name: "pobyt na OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "500",
    },
    {
      name: "Opracja chirurgiczna:",
      pzu: null,
      hestia: null,
      warta: "s.u. 2000",
    },
    {
      name: "I klasa",
      pzu: "1500",
      hestia: "2000",
      warta: null,
    },
    {
      name: "II klasa",
      pzu: "750",
      hestia: "1200",
      warta: null,
    },
    {
      name: "III klasa",
      pzu: "500",
      hestia: "400",
      warta: null,
    },
    {
      name: "IVklasa",
      pzu: "150",
      hestia: null,
      warta: null,
    },
    {
      name: "Vklasa",
      pzu: "75",
      hestia: null,
      warta: null,
    },
    {
      name: "całkowita niezdolność do pracy ubezpieczonego w wyniku NW",
      pzu: null,
      hestia: "40000",
      warta: "45000",
    },
    {
      name: "niezdolność do samodzilnej egzystencji",
      pzu: null,
      hestia: null,
      warta: "15000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku NW-za 1% trwałego uszczerbku",
      pzu: "200",
      hestia: "500",
      warta: "480",
    },
    {
      name: "śmierć małżonka w wyniku NW komunikacyjnego",
      pzu: "20000",
      hestia: "24000",
      warta: "30000",
    },
    {
      name: "śmierć małżonka w wyniku NW",
      pzu: "20000",
      hestia: "24000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka w wyniku zawału serca lub udaru mózgu",
      pzu: "10000",
      hestia: "12000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka niezależnie od przyczyny",
      pzu: "10000",
      hestia: "12000",
      warta: "10000",
    },
    {
      name: "trwałe inwalidztwo małżonka/partnera w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "ciężka choroba małżonka/partnera",
      pzu: "3000",
      hestia: "3000",
      warta: null,
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku choroby/NW",
      pzu: "50/100",
      hestia: null,
      warta: "40/100",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "200",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku zawału serca/udaru mózgu",
      pzu: "50",
      hestia: null,
      warta: "100",
    },
    {
      name: "pobyt małżonka/partnerana OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "400",
    },
    {
      name: "osierocenie dziecka",
      pzu: null,
      hestia: "4000",
      warta: "300",
    },
    {
      name: "urodzenie dziecka",
      pzu: "1000",
      hestia: "1300",
      warta: "1000",
    },
    {
      name: "urodzenie marwego dziecka",
      pzu: null,
      hestia: "2600",
      warta: null,
    },
    {
      name: "wada wrodzona dziecka",
      pzu: null,
      hestia: "2500",
      warta: "3000",
    },
    {
      name: "trwałe inwalidztwo dziecka w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "śmierć dziecka spowodowana NW",
      pzu: "6000",
      hestia: "10000",
      warta: "6000",
    },
    {
      name: "śmierć dziecka niezależnie od przyczyny",
      pzu: "3000",
      hestia: "5000",
      warta: "3000",
    },
    {
      name: "ciężka choroba dziacka",
      pzu: "4000",
      hestia: "5000",
      warta: "4000",
    },
    {
      name: "leczenie szpitalne dziecka-za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "50/100",
      hestia: "500 (kwota zryczałtowana)",
      warta: "40/100",
    },
    {
      name: "rekonwalescencja",
      pzu: null,
      hestia: null,
      warta: "1000",
    },
    {
      name: "śmierć noworodka",
      pzu: null,
      hestia: null,
      warta: "3000",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera spowodowana NW",
      pzu: "3000",
      hestia: "1600",
      warta: "3500",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera niezależnie od przyczyny",
      pzu: "1200",
      hestia: "1600",
      warta: "1500",
    },
  ],
  "54": [
    {
      name: "składka miesięczna",
      pzu: "117",
      hestia: "151",
      warta: "111",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym w pracy",
      pzu: "260000",
      hestia: "220000",
      warta: "175000",
    },
    {
      name: "śmierć spowodowana wypadkiem w pracy",
      pzu: "220000",
      hestia: "150000",
      warta: "110000",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym",
      pzu: "200000",
      hestia: "150000",
      warta: "145000",
    },
    {
      name: "śmierć spowodowana nieszczęśliwym wypadkiem (NW)",
      pzu: "160000",
      hestia: "100000",
      warta: "85000",
    },
    {
      name: "śmierć spowodowana zawałem serce lub udarem mózgu",
      pzu: "55000",
      hestia: "65000",
      warta: "80000",
    },
    {
      name: "śmierć niezależnie od przyczyny",
      pzu: "55000",
      hestia: "50000",
      warta: "35000",
    },
    {
      name: "zachorowanie na ciężką chorobę",
      pzu: "3000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "zachorowanie na nowotwór złośliwy",
      pzu: "9000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "wystąpienie nowotworu we wczesnym stadium",
      pzu: "1000",
      hestia: null,
      warta: null,
    },
    {
      name: "leczenie specjalistyczne",
      pzu: "2000",
      hestia: "do 2500",
      warta: "2000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku zawału serca lub udaru śródmózgowego -za 1% uszczerbku",
      pzu: null,
      hestia: "400",
      warta: null,
    },
    {
      name: "usługi assistance",
      pzu: "TAK",
      hestia: "NIE",
      warta: null,
    },
    {
      name: "Lecznie szpitalne (skumulowane kwoty świadczeń):",
      pzu: null,
      hestia: null,
      warta: null,
    },
    {
      name: "za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "60/120",
      hestia: "70/180",
      warta: "80/160",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku komunikacyjngo przy pracy",
      pzu: "120",
      hestia: "330",
      warta: "440",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku przy pracy",
      pzu: "120",
      hestia: "180",
      warta: "250",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku NW w ruchu lądowym, wodnym lub powietrznym",
      pzu: "120",
      hestia: "330",
      warta: "330",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku zawału serca lub krwotoku śródmózgowego-za 1%",
      pzu: "60",
      hestia: "140",
      warta: "150",
    },
    {
      name: "pobyt na OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "500",
    },
    {
      name: "Opracja chirurgiczna:",
      pzu: null,
      hestia: null,
      warta: "s.u. 2000",
    },
    {
      name: "I klasa",
      pzu: "1500",
      hestia: "2000",
      warta: null,
    },
    {
      name: "II klasa",
      pzu: "750",
      hestia: "1200",
      warta: null,
    },
    {
      name: "III klasa",
      pzu: "500",
      hestia: "400",
      warta: null,
    },
    {
      name: "IVklasa",
      pzu: "150",
      hestia: null,
      warta: null,
    },
    {
      name: "Vklasa",
      pzu: "75",
      hestia: null,
      warta: null,
    },
    {
      name: "całkowita niezdolność do pracy ubezpieczonego w wyniku NW",
      pzu: null,
      hestia: "40000",
      warta: "45000",
    },
    {
      name: "niezdolność do samodzilnej egzystencji",
      pzu: null,
      hestia: null,
      warta: "15000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku NW-za 1% trwałego uszczerbku",
      pzu: "235",
      hestia: "500",
      warta: "480",
    },
    {
      name: "śmierć małżonka w wyniku NW komunikacyjnego",
      pzu: "20000",
      hestia: "24000",
      warta: "30000",
    },
    {
      name: "śmierć małżonka w wyniku NW",
      pzu: "20000",
      hestia: "24000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka w wyniku zawału serca lub udaru mózgu",
      pzu: "10000",
      hestia: "12000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka niezależnie od przyczyny",
      pzu: "10000",
      hestia: "12000",
      warta: "10000",
    },
    {
      name: "trwałe inwalidztwo małżonka/partnera w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "ciężka choroba małżonka/partnera",
      pzu: "3000",
      hestia: "3000",
      warta: null,
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku choroby/NW",
      pzu: "50/100",
      hestia: null,
      warta: "40/100",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "200",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku zawału serca/udaru mózgu",
      pzu: "50",
      hestia: null,
      warta: "100",
    },
    {
      name: "pobyt małżonka/partnerana OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "400",
    },
    {
      name: "osierocenie dziecka",
      pzu: null,
      hestia: "4000",
      warta: "300",
    },
    {
      name: "urodzenie dziecka",
      pzu: "1000",
      hestia: "1300",
      warta: "1000",
    },
    {
      name: "urodzenie marwego dziecka",
      pzu: null,
      hestia: "2600",
      warta: null,
    },
    {
      name: "wada wrodzona dziecka",
      pzu: null,
      hestia: "2500",
      warta: "3000",
    },
    {
      name: "trwałe inwalidztwo dziecka w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "śmierć dziecka spowodowana NW",
      pzu: "6000",
      hestia: "10000",
      warta: "6000",
    },
    {
      name: "śmierć dziecka niezależnie od przyczyny",
      pzu: "3000",
      hestia: "5000",
      warta: "3000",
    },
    {
      name: "ciężka choroba dziacka",
      pzu: "4000",
      hestia: "5000",
      warta: "4000",
    },
    {
      name: "leczenie szpitalne dziecka-za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "50/100",
      hestia: "500 (kwota zryczałtowana)",
      warta: "40/100",
    },
    {
      name: "rekonwalescencja",
      pzu: null,
      hestia: null,
      warta: "1000",
    },
    {
      name: "śmierć noworodka",
      pzu: null,
      hestia: null,
      warta: "3000",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera spowodowana NW",
      pzu: "3000",
      hestia: "1600",
      warta: "3500",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera niezależnie od przyczyny",
      pzu: "1200",
      hestia: "1600",
      warta: "1500",
    },
  ],
  "55-59": [
    {
      name: "składka miesięczna",
      pzu: "117",
      hestia: "151",
      warta: "152",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym w pracy",
      pzu: "260000",
      hestia: "220000",
      warta: "175000",
    },
    {
      name: "śmierć spowodowana wypadkiem w pracy",
      pzu: "220000",
      hestia: "150000",
      warta: "110000",
    },
    {
      name: "śmierć spowodowana wypadkiem komunikacyjnym",
      pzu: "200000",
      hestia: "150000",
      warta: "145000",
    },
    {
      name: "śmierć spowodowana nieszczęśliwym wypadkiem (NW)",
      pzu: "160000",
      hestia: "100000",
      warta: "85000",
    },
    {
      name: "śmierć spowodowana zawałem serce lub udarem mózgu",
      pzu: "55000",
      hestia: "65000",
      warta: "80000",
    },
    {
      name: "śmierć niezależnie od przyczyny",
      pzu: "55000",
      hestia: "50000",
      warta: "35000",
    },
    {
      name: "zachorowanie na ciężką chorobę",
      pzu: "3000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "zachorowanie na nowotwór złośliwy",
      pzu: "1000",
      hestia: "9000",
      warta: "5000",
    },
    {
      name: "wystąpienie nowotworu we wczesnym stadium",
      pzu: "1000",
      hestia: null,
      warta: null,
    },
    {
      name: "leczenie specjalistyczne",
      pzu: "2000",
      hestia: "do 2500",
      warta: "2000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku zawału serca lub udaru śródmózgowego -za 1% uszczerbku",
      pzu: null,
      hestia: "400",
      warta: null,
    },
    {
      name: "usługi assistance",
      pzu: "TAK",
      hestia: "NIE",
      warta: null,
    },
    {
      name: "Lecznie szpitalne (skumulowane kwoty świadczeń):",
      pzu: null,
      hestia: null,
      warta: null,
    },
    {
      name: "za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "60/120",
      hestia: "70/180",
      warta: "80/160",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku komunikacyjngo przy pracy",
      pzu: "120",
      hestia: "330",
      warta: "440",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku wypadku przy pracy",
      pzu: "120",
      hestia: "180",
      warta: "250",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku NW w ruchu lądowym, wodnym lub powietrznym",
      pzu: "120",
      hestia: "330",
      warta: "330",
    },
    {
      name: "za dzień pobytu w szpitalu w wyniku zawału serca lub krwotoku śródmózgowego-za 1%",
      pzu: "60",
      hestia: "140",
      warta: "150",
    },
    {
      name: "pobyt na OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "500",
    },
    {
      name: "Opracja chirurgiczna:",
      pzu: null,
      hestia: null,
      warta: "s.u. 2000",
    },
    {
      name: "I klasa",
      pzu: "1500",
      hestia: "2000",
      warta: null,
    },
    {
      name: "II klasa",
      pzu: "750",
      hestia: "1200",
      warta: null,
    },
    {
      name: "III klasa",
      pzu: "500",
      hestia: "400",
      warta: null,
    },
    {
      name: "IVklasa",
      pzu: "150",
      hestia: null,
      warta: null,
    },
    {
      name: "Vklasa",
      pzu: "75",
      hestia: null,
      warta: null,
    },
    {
      name: "całkowita niezdolność do pracy ubezpieczonego w wyniku NW",
      pzu: null,
      hestia: "40000",
      warta: "45000",
    },
    {
      name: "niezdolność do samodzilnej egzystencji",
      pzu: null,
      hestia: null,
      warta: "15000",
    },
    {
      name: "uszczerbek na zdrowiu w wyniku NW-za 1% trwałego uszczerbku",
      pzu: "235",
      hestia: "500",
      warta: "480",
    },
    {
      name: "śmierć małżonka w wyniku NW komunikacyjnego",
      pzu: "20000",
      hestia: "24000",
      warta: "30000",
    },
    {
      name: "śmierć małżonka w wyniku NW",
      pzu: "20000",
      hestia: "24000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka w wyniku zawału serca lub udaru mózgu",
      pzu: "10000",
      hestia: "12000",
      warta: "20000",
    },
    {
      name: "śmierć małżonka niezależnie od przyczyny",
      pzu: "10000",
      hestia: "12000",
      warta: "10000",
    },
    {
      name: "trwałe inwalidztwo małżonka/partnera w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "ciężka choroba małżonka/partnera",
      pzu: "3000",
      hestia: "3000",
      warta: null,
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku choroby/NW",
      pzu: "50/100",
      hestia: null,
      warta: "40/100",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "200",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku wypadku komunikacyjnego w pracy",
      pzu: "100",
      hestia: null,
      warta: "140",
    },
    {
      name: "leczenie szpitalne małżonka/partnera-za dzień pobytu w szpitalu w wyniku zawału serca/udaru mózgu",
      pzu: "50",
      hestia: null,
      warta: "100",
    },
    {
      name: "pobyt małżonka/partnerana OIOM-ie (jednorazowa kwota)",
      pzu: null,
      hestia: null,
      warta: "400",
    },
    {
      name: "osierocenie dziecka",
      pzu: null,
      hestia: "4000",
      warta: "300",
    },
    {
      name: "urodzenie dziecka",
      pzu: "1000",
      hestia: "1300",
      warta: "1000",
    },
    {
      name: "urodzenie marwego dziecka",
      pzu: null,
      hestia: "2600",
      warta: null,
    },
    {
      name: "wada wrodzona dziecka",
      pzu: null,
      hestia: "2500",
      warta: "3000",
    },
    {
      name: "trwałe inwalidztwo dziecka w wyniku NW",
      pzu: null,
      hestia: "do 10 000",
      warta: null,
    },
    {
      name: "śmierć dziecka spowodowana NW",
      pzu: "6000",
      hestia: "10000",
      warta: "6000",
    },
    {
      name: "śmierć dziecka niezależnie od przyczyny",
      pzu: "3000",
      hestia: "5000",
      warta: "3000",
    },
    {
      name: "ciężka choroba dziacka",
      pzu: "4000",
      hestia: "5000",
      warta: "4000",
    },
    {
      name: "leczenie szpitalne dziecka-za dzień pobytu w szpitalu spowodowanego chorobą/NW",
      pzu: "50/100",
      hestia: "500 (kwota zryczałtowana)",
      warta: "40/100",
    },
    {
      name: "rekonwalescencja",
      pzu: null,
      hestia: null,
      warta: "1000",
    },
    {
      name: "śmierć noworodka",
      pzu: null,
      hestia: null,
      warta: "3000",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera spowodowana NW",
      pzu: "3000",
      hestia: "1600",
      warta: "3500",
    },
    {
      name: "śmierć rodzica lub rodzica małżonka/parnera niezależnie od przyczyny",
      pzu: "1200",
      hestia: "1600",
      warta: "1500",
    },
  ],
};
